### ISSUE TITLE
Compatibility with streamlit-option-menu

### ISSUE THREAD

**Issue by dcorallo** [franekp/streamlit-permalink#1]
Are there any plans to support https://github.com/victoryhb/streamlit-option-menu ?

**Comment by franekp** [comment]
This makes sense. I think that this should be opt-in, behind a feature flag (e.g. like [here](https://stackoverflow.com/questions/52474931/what-is-extra-in-pypi-dependency)). While I don't have time to implement it any time soon, pull requests are welcome.

**Comment by franekp** [comment]
Done. [Version 0.5.0](https://pypi.org/project/streamlit-permalink/0.5.0/) detects whether streamlit-option-menu is installed and adds `stp.option_menu` component. No feature flag is needed for this to work.
